import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
const AddNodeModal = ({ isOpen, onClose, onAdd }) => {
    const [formData, setFormData] = useState({ name: '', ip: '', model: 'YOLOv8m-parking' });
    if (!isOpen)
        return null;
    return (_jsx("div", { className: "fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50", children: _jsxs("div", { className: "bg-[#1a1c23] border border-gray-700 p-8 rounded-xl w-[400px] shadow-2xl", children: [_jsx("h2", { className: "text-xl font-bold text-white mb-6", children: "Provision New Edge Node" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "text-xs text-gray-400 uppercase", children: "Node Name" }), _jsx("input", { type: "text", className: "w-full bg-[#0d0e12] border border-gray-600 rounded p-2 text-white focus:border-blue-500 outline-none", placeholder: "e.g. North Parking Entrance", value: formData.name, onChange: (e) => setFormData({ ...formData, name: e.target.value }) })] }), _jsxs("div", { children: [_jsx("label", { className: "text-xs text-gray-400 uppercase", children: "Stream URL (RTSP/IP)" }), _jsx("input", { type: "text", className: "w-full bg-[#0d0e12] border border-gray-600 rounded p-2 text-white outline-none focus:border-blue-500", placeholder: "192.168.0.XX", value: formData.ip, onChange: (e) => setFormData({ ...formData, ip: e.target.value }) })] }), _jsxs("div", { children: [_jsx("label", { className: "text-xs text-gray-400 uppercase", children: "AI Model" }), _jsxs("select", { className: "w-full bg-[#0d0e12] border border-gray-600 rounded p-2 text-white outline-none focus:border-blue-500", value: formData.model, onChange: (e) => setFormData({ ...formData, model: e.target.value }), children: [_jsx("option", { value: "YOLOv8m-parking", children: "YOLOv8m Parking Analytics" }), _jsx("option", { value: "YOLOv8m-safety", children: "YOLOv8m Safety Gear Detector" }), _jsx("option", { value: "YOLOv8n-general", children: "YOLOv8n General Purpose" })] })] })] }), _jsxs("div", { className: "flex gap-4 mt-8", children: [_jsx("button", { onClick: onClose, className: "flex-1 px-4 py-2 border border-gray-600 text-gray-400 rounded hover:bg-gray-800 transition", children: "Cancel" }), _jsx("button", { onClick: () => onAdd(formData), className: "flex-1 px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-500 transition font-bold", children: "Deploy Node" })] })] }) }));
};
export default AddNodeModal;
