import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Activity, Menu, X } from 'lucide-react';
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
export default function Navbar() {
    const [isScrolled, setIsScrolled] = useState(false);
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    useEffect(() => {
        const handleScroll = () => {
            setIsScrolled(window.scrollY > 20);
        };
        window.addEventListener('scroll', handleScroll);
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);
    return (_jsxs("nav", { className: `fixed top-0 w-full z-50 transition-all duration-300 ${isScrolled ? 'glass py-3' : 'bg-transparent py-5'}`, children: [_jsxs("div", { className: "container mx-auto px-6 md:px-12 flex justify-between items-center", children: [_jsxs("div", { className: "flex items-center gap-2 cursor-pointer group", children: [_jsx("div", { className: "relative flex items-center justify-center p-2 rounded-lg bg-neon-blue/10 border border-neon-blue/30 group-hover:neon-border transition-all duration-300", children: _jsx(Activity, { className: "w-6 h-6 text-neon-blue animate-pulse-slow" }) }), _jsxs("span", { className: "text-xl font-bold tracking-tight text-white group-hover:text-glow transition-all", children: ["Vision", _jsx("span", { className: "text-neon-blue", children: "AIoT" })] })] }), _jsxs("div", { className: "hidden md:flex items-center gap-8 text-sm font-medium text-slate-300", children: [_jsx("a", { href: "#features", className: "hover:text-neon-blue transition-colors", children: "Features" }), _jsx("a", { href: "#solutions", className: "hover:text-neon-blue transition-colors", children: "Solutions" }), _jsx("a", { href: "#roadmap", className: "hover:text-neon-blue transition-colors", children: "Roadmap" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-4", children: [_jsx("button", { className: "text-sm font-medium text-slate-300 hover:text-white transition-colors", children: "Read Whitepaper" }), _jsx(Link, { to: "/dashboard", className: "px-5 py-2.5 rounded-lg bg-neon-blue/10 text-neon-blue border border-neon-blue/50 hover:bg-neon-blue/20 hover:neon-border transition-all duration-300 font-medium text-sm flex items-center gap-2", children: "Launch Dashboard" })] }), _jsx("button", { className: "md:hidden text-slate-300 hover:text-white", onClick: () => setMobileMenuOpen(!mobileMenuOpen), children: mobileMenuOpen ? _jsx(X, { className: "w-6 h-6" }) : _jsx(Menu, { className: "w-6 h-6" }) })] }), mobileMenuOpen && (_jsxs("div", { className: "md:hidden glass absolute top-full left-0 w-full border-t border-slate-700/50 flex flex-col p-4 gap-4", children: [_jsx("a", { href: "#features", className: "text-slate-300 hover:text-neon-blue p-2", children: "Features" }), _jsx("a", { href: "#solutions", className: "text-slate-300 hover:text-neon-blue p-2", children: "Solutions" }), _jsx("a", { href: "#roadmap", className: "text-slate-300 hover:text-neon-blue p-2", children: "Roadmap" }), _jsx("div", { className: "h-px bg-slate-700/50 w-full my-2" }), _jsx("button", { className: "text-slate-300 hover:text-white w-full text-left p-2", children: "Read Whitepaper" }), _jsx(Link, { to: "/dashboard", className: "w-full text-center px-5 py-3 rounded-lg bg-neon-blue/10 text-neon-blue border border-neon-blue/50 font-medium mt-2 block", children: "Launch Dashboard" })] }))] }));
}
